### ISSUE TITLE
Usage example fails

### ISSUE THREAD

**Issue by stevemarple** [aaren/wavelets#4]
The usage example given in README.md fails on the line
```python

power = wa.wavelet_power
```
with the error
````
ValueError: could not broadcast input array from shape (1042) into shape (1000)
````

Python version is 2.7.3, numpy version is 1.7.1, scipy version is 0.10.1.

**Comment by aaren** [comment]
@stevemarple is this still a problem for you with the latest code?

I can't replicate this now so possibly I fixed it recently. If it is still a problem we can reopen this issue.
